name: Tests

on:
  push:
    branches:
      - master
      - ci
      - "releases/*"
  pull_request:
    branches:
      - '*'
  schedule:
    - cron: "0 */6 * * *"

env:
  RUST_TEST_THREADS: 2

jobs:
  test:
    runs-on: ${{ matrix.os }}
    timeout-minutes: 35
    strategy:
      matrix:
        os: [macos-latest]
        # migrations tests work only on nightly
        edgedb-version: ["nightly"]
    steps:
      - uses: actions/checkout@master
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          default: true
      - uses: Swatinem/rust-cache@v1

      - uses: actions-rs/cargo@v1
        with:
          command: test
          args: --features github_action_install install::github_action_install
